@startuml

title __REQUEST's Class Diagram__\n

  namespace omsu.imit {
    namespace dto.request {
      class omsu.imit.dto.request.InnInfoRequest {
          - inn : long
          - name : String
          - startFrom : LocalDateTime
          + InnInfoRequest()
          + InnInfoRequest()
          + getInn()
          + getName()
          + getStartFrom()
          + setInn()
          + setName()
          + setStartFrom()
      }
    }
  }
  

  namespace omsu.imit {
    namespace dto.request {
      class omsu.imit.dto.request.OfdTokenRequest {
          - Login : String
          - Password : String
          + OfdTokenRequest()
          + getLogin()
          + getPassword()
          + setLogin()
          + setPassword()
      }
    }
  }
  

  namespace omsu.imit {
    namespace dto.request {
      class omsu.imit.dto.request.ReceiptRequest {
          - date : String
          - id : long
          + ReceiptRequest()
          + ReceiptRequest()
          + getDate()
          + getId()
          + setDate()
          + setId()
      }
    }
  }
  

  namespace omsu.imit {
    namespace dto.request {
      class omsu.imit.dto.request.ReportRequest {
          - from : String
          - kkts : List<String>
          - to : String
          + ReportRequest()
          + ReportRequest()
          + getFrom()
          + getKkts()
          + getTo()
          + setFrom()
          + setKkts()
          + setTo()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
